name: NikkiWhite
favicon: null
layout_spectrum: 0.5144260013476014
typography_spectrum: 0.059733572881668806
title: Insight into the world of Nikki White
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d5d9cb'
    - '#5b7d37'
    - '#101f11'
    - '#9db73b'
  brandStrength: 0.9454277600161731
  lightness: 0.9266114195343107
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
