name: NikkiWhite
favicon: null
layout_spectrum: 0.5144260013476014
typography_spectrum: 0.059733572881668806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9454277600161731
  lightness: 0.9266114195343107
  saturation: 0.9522915473207831
  rhythmicContrast: 0.9672967188525945
purpose: []
